name: build

on: # Controls when the workflow will run
  push: # Triggers the workflow on push events but only for the develop or main branches
    branches: [develop, main]
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  build: # This workflow contains a single job called "build"
    runs-on: [self-hosted, Linux, X64, BuildMachine] # The type of runner that the job will run on
    
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      - run: rm -rf var-fslc-yocto # clean
      
      - run: |
          mkdir var-fslc-yocto
          cd var-fslc-yocto
          repo init -u https://github.com/varigit/variscite-bsp-platform.git -b 05082844a2bf88295974f89a56daa9389ec5e10a
          repo sync
          
          export EULA=1
          MACHINE=var-som-mx6 DISTRO=fslc-framebuffer source setup-environment build
          
          echo 'INHERIT += "rm_work"'                      >> conf/local.conf
          echo 'DL_DIR = "/mnt/resource/downloads"'        >> conf/local.conf
          echo 'SSTATE_DIR = "/mnt/resource/sstate-cache"' >> conf/local.conf
          
          bitbake fsl-image-gui

      - uses: actions/upload-artifact@v2
        with:
          name: sdcard
          path: var-fslc-yocto/build/tmp/deploy/images/var-som-mx6/*.rootfs.wic.gz

      - run: rm -rf var-fslc-yocto # clean
