name: neu2a yocto Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: neu2a yocto Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          rm -rf neu2aYctBuild
          mkdir neu2aYctBuild
          cd neu2aYctBuild
          sudo apt-get update
                  sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio  xz-utils debianutils iputils-ping libsdl1.2-dev xterm

      - name: Clone Yocto Poky repository
        run: |
          cd neu2aYctBuild
          git clone git://git.yoctoproject.org/poky.git  
          
      - name: Check directory contents
        run: |
          cd neu2aYctBuild
          ls
      
      - name: Clone bitbake repository
        run: |
          cd neu2aYctBuild  
          pwd
          ls
          git clone git://git.openembedded.org/bitbake -b master 
          ls
          
      - name: Clone openembedded-core repository
        run: |
          cd neu2aYctBuild
          git clone git://git.openembedded.org/openembedded-core -b kirkstone  

      - name: Clone meta-arm repository
        run: |
         cd neu2aYctBuild
         git clone git://git.yoctoproject.org/meta-arm -b kirkstone  

      - name: Clone meta-openembedded repository
        run: |
         cd neu2aYctBuild
         git clone git://git.openembedded.org/meta-openembedded -b kirkstone  

      - name: Clone meta-neu6b repo
        run: | 
          cd neu2aYctBuild
          git clone https://github.com/manojams/meta-neu6b.git -b kirkstone 
      
      - name: Print current directory
        run: |
          cd neu2aYctBuild
          pwd

      - name: Check directory contents
        run: |
          cd neu2aYctBuild
          ls
          
      - name: Build neu2a-io yocto build
        run: |
          cd neu2aYctBuild
          ls
          source openembedded-core/oe-init-build-env
          
      - name: Check directory contents
        run: |
           cd neu2aYctBuild
           ls
          
      - name: setup the local.conf and bblayer.conf
        run: |
          cd neu2aYctBuild
          ls
          source openembedded-core/oe-init-build-env build
          echo 'BBLAYERS:append = "${TOPDIR}/../meta-neu6b"' >> conf/bblayers.conf
          echo 'BBLAYERS:append = "${TOPDIR}/../meta-openembedded/meta-oe"' >> conf/bblayers.conf
          echo 'BBLAYERS:append =  "${TOPDIR}/../meta-openembedded/meta-python"' >> conf/bblayers.conf
          echo 'BBLAYERS:append =  "${TOPDIR}/../poky/meta"' >> conf/bblayers.conf
          echo 'BBLAYERS:append =  "${TOPDIR}/../meta-arm/meta-arm-toolchain"' >> conf/bblayers.conf
          echo 'BBLAYERS:append =  "${TOPDIR}/../meta-arm/meta-arm"' >> conf/bblayers.conf
          cat conf/bblayers.conf
          bitbake core-image-minimal
          

      # Add additional steps if needed, such as deploying the build artifacts
